services:
  ecommerce-app: 
    build:
      context: . # build from dockerfile
      target: development
    volumes:
      - ./src:/app/src
      # - ./src:/app/src:ro   => read only
    environment:
      - NODE_ENV=development
