# services (means containers, any apps or databases)
services:
  ecommerce-app: # (app/service name) you can give it any name
    container_name: ecommerce-app-container
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ./config.env

  # Now mongoDB service
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db      # the directory to store data on (from mongo documentation) | its name is determined down as mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongo-db:   # volume name to store data
